cmsc424-fall2016-master/project2/gradingsite/grading/urls.py
from django.conf.urls import url

from . import views
        
urlpatterns = [
        # ex: /grading/
        url(r'^$', views.mainindex, name='mainindex'),
        # ex: /grading/instructor/1
        url(r'^instructor/(?P<instructor_id>[0-9]+)/$', views.instructorindex, name='instructorindex'),
        # ex: /grading/instructor/1/course/2
        url(r'^instructor/(?P<instructor_id>[0-9]+)/course/(?P<course_id>[0-9]+)/$', views.instructorcourse, name='instructorcourse'),
        # ex: /grading/instructor/1/course/2/assignment/3
        url(r'^instructor/(?P<instructor_id>[0-9]+)/course/(?P<course_id>[0-9]+)/assignment/(?P<assignment_id>[0-9]+)/$', views.instructorassignment, name='instructorassignment'),
        # ex: /grading/instructor/1/course/2/create
        url(r'^instructor/(?P<instructor_id>[0-9]+)/course/(?P<course_id>[0-9]+)/create$', views.instructorcreate, name='instructorcreate'),
        # ex: /grading/instructor/1/course/2/assignment/3/student/4
        url(r'^instructor/(?P<instructor_id>[0-9]+)/course/(?P<course_id>[0-9]+)/assignment/(?P<assignment_id>[0-9]+)/student/(?P<student_id>[0-9]+)/$', views.instructorgradesubmission, name='instructorgradesubmission'),
        # ex: /grading/student/1
        url(r'^student/(?P<student_id>[0-9]+)/$', views.studentindex, name='studentindex'),
        # ex: /grading/student/1/assignment/2
        url(r'^student/(?P<student_id>[0-9]+)/assignment/(?P<assignment_id>[0-9]+)/$', views.studentassignment, name='studentassignment'),
        # ex: /grading/student/1/submitassignment/2
        url(r'^student/(?P<student_id>[0-9]+)/submitassignment/(?P<assignment_id>[0-9]+)/$', views.submitassignment, name='submitassignment'),
        # ex: /grading/student/1/submittedassignment/2
        url(r'^student/(?P<student_id>[0-9]+)/submittedassignment/(?P<assignment_id>[0-9]+)/$', views.submittedassignment, name='submittedassignment')
] 

cmsc424-fall2016-master/project2/gradingsite/gradingsite/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^grading/', include('grading.urls')),
    url(r'^admin/', admin.site.urls),
]

cmsc424-fall2016-master/project2/gradingsite/grading/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.
import datetime
from django.utils import timezone

class Instructor(models.Model):
	name = models.CharField(max_length=50)
	rank = models.CharField(max_length=50)
	def __str__(self):
		return self.name

class Course(models.Model):
	title = models.CharField(max_length=50)
    	instructor = models.ForeignKey(Instructor, on_delete=models.CASCADE)
	credits = models.IntegerField()
	description = models.CharField(max_length=500)
	def __str__(self):
		return self.title

class Student(models.Model):
	name = models.CharField(max_length=50)
	courses = models.ManyToManyField(Course)
	def __str__(self):
		return self.name

class Assignment(models.Model):
	course = models.ForeignKey(Course)
	assignment_no = models.IntegerField()
	due_date = models.DateTimeField()
	def __str__(self):
		return "Course Title: {}, Assignment No.: {}, Due on: {}".format(self.course.title, self.assignment_no, self.due_date)

class Question(models.Model):
	assignment = models.ForeignKey(Assignment)
	question_no = models.IntegerField()
	question_text = models.CharField(max_length=500)
	trueorfalse = models.BooleanField()

class StudentAssignment(models.Model):
	assignment = models.ForeignKey(Assignment)
	student = models.ForeignKey(Student)
	answers = models.CharField(max_length=100)
	score = models.IntegerField()
	

cmsc424-fall2016-master/project2/gradingsite/grading/views.py
from django.shortcuts import render, get_object_or_404

from django.http import HttpResponse, HttpResponseRedirect
from grading.models import Instructor, Course, Assignment, Student, StudentAssignment
from django.urls import reverse
import datetime
from django.utils import timezone


# Create your views here.

def mainindex(request):
        context = { 'instructor_list': Instructor.objects.all() }
        return render(request, 'grading/index.html', context)

def instructorindex(request, instructor_id):
        context = { 'course_list': Instructor.objects.get(pk=instructor_id).course_set.all() }
        return render(request, 'grading/instructorindex.html', context)

def instructorcourse(request, instructor_id, course_id):
	c = get_object_or_404(Course, pk=course_id)
	a_list = c.assignment_set.filter(due_date__gte=timezone.now())
	p_list = c.assignment_set.filter(due_date__lte=timezone.now())
	context = { 'instructor_id': instructor_id, 'course_id': course_id, 'course_title': c.title, 'active_assignment_list': a_list, 'past_assignment_list': p_list }
        return render(request, 'grading/instructorcourse.html', context)

def instructorassignment(request, instructor_id, course_id, assignment_id):
	# Should get a list of all submissions for this assignment, and set it in context
        context = { }
        return render(request, 'grading/instructorassignment.html', context)

def instructorcreate(request, instructor_id, course_id):
        context = { 'course_list': Instructor.objects.all() }
        return render(request, 'grading/instructorcreate.html', context)

def instructorgradesubmission(request, instructor_id, course_id, assignment_id, student_id):
	context = { }
        return render(request, 'grading/instructorgradesubmission.html', context)

def studentindex(request, student_id):
	context = { 'student_id': student_id, 'course_list': Student.objects.get(pk=student_id).courses.all() }
        return render(request, 'grading/studentindex.html', context)

def studentassignment(request, student_id, assignment_id):
	context = { 'assignment': Assignment.objects.get(pk=assignment_id), 'student': Student.objects.get(pk=student_id) }
        return render(request, 'grading/studentassignment.html', context)

def submitassignment(request, student_id, assignment_id):
	print request.POST
	answers = " ".join([request.POST["answer{}".format(i)] for i in range(1, 101) if "answer{}".format(i) in request.POST])
	sa = StudentAssignment(student=Student.objects.get(pk=student_id), assignment=Assignment.objects.get(pk=assignment_id), answers=answers, score=-1)
	sa.save()
	return HttpResponseRedirect(reverse('submittedassignment', args=(student_id,assignment_id,)))

def submittedassignment(request, student_id, assignment_id):
	context = { 'student_id': student_id, 'course_list': Student.objects.get(pk=student_id).courses.all() }
	return render(request, 'grading/studentindex.html', context)

cmsc424-fall2016-master/project2/gradingsite/grading/templates/grading/default.html
<b>You need to write the template code to implement the required functionality. Look at the other files in this directory for some examples. </b><br><br><br>

<b>The below shows some debug output. The important one here is the first part -- which shows the "context". </b><br><br><br>

{% debug %}

cmsc424-fall2016-master/project2/gradingsite/grading/templates/grading/index.html
{% if instructor_list %}
Who are you?
    <ul>
    {% for i in instructor_list %}
        <li><a href="/grading/instructor/{{ i.id }}/">{{ i.name }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No instructors are available.</p>
{% endif %}

cmsc424-fall2016-master/project2/gradingsite/grading/templates/grading/instructorassignment.html
<b>You need to write the template code to implement the required functionality. Look at the other files in this directory for some examples. </b><br><br><br>

<b>The below shows some debug output. The important one here is the first part -- which shows the "context". </b><br><br><br>

{% debug %}

cmsc424-fall2016-master/project2/gradingsite/grading/templates/grading/instructorcourse.html
<h3> Active Assignments for {{ course_title }} </h3>
{% if active_assignment_list %}
<ul>
    {% for a in active_assignment_list %}
    <li> <a href="/grading/instructor/{{ instructor_id }}/course/{{ course_id }}/assignment/{{ a.id }}">Assignment {{ a.assignment_no }}, Due Date: {{ a.due_date }} </a>
    {% endfor %}
</ul>
{% else %}
No active assignments.  
{% endif %}

<h3> Past Assignments for {{ course_title }} </h3>
{% if past_assignment_list %}
<ul>
    {% for a in past_assignment_list %}
    <li> <a href="/grading/instructor/{{ instructor_id }}/course/{{ course_id }}/assignment/{{ a.id }}">Assignment {{ a.assignment_no }}, Due Date: {{ a.due_date }} </a>
    {% endfor %}
</ul>
{% else %}
No past assignments.  
{% endif %}

cmsc424-fall2016-master/project2/gradingsite/grading/templates/grading/instructorgradesubmission.html
<b>You need to write the template code to implement the required functionality. Look at the other files in this directory for some examples. </b><br><br><br>

<b>The below shows some debug output. The important one here is the first part -- which shows the "context". </b><br><br><br>

{% debug %}

cmsc424-fall2016-master/project2/gradingsite/grading/templates/grading/instructorindex.html
<b>You need to write the template code to implement the required functionality. Look at the other files in this directory for some examples. </b><br><br><br>

<b>The below shows some debug output. The important one here is the first part -- which shows the "context". </b><br><br><br>

{% debug %}

cmsc424-fall2016-master/project2/gradingsite/grading/templates/grading/studentassignment.html
Assignment No.: {{ assignment.assignment_no }}

<form action="/grading/student/{{ student.id }}/submitassignment/{{ assignment.id }}/" method="post">
{% csrf_token %}
<ul>
{% for q in assignment.question_set.all %}
<li> Question {{ q.question_no }}: {{ q.question_text }} &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 
<label>True <input type="radio" name="answer{{ q.question_no }}"  value="true" checked="checked"/> </label> 
<label>False <input type="radio" name="answer{{ q.question_no }}"  value="false" /> </label>
{% endfor %}
</ul>
<input type="submit" value="Submit Assignment" />
</form>

cmsc424-fall2016-master/project2/gradingsite/grading/templates/grading/studentindex.html
{% if course_list %}
    {% for c in course_list %}
    <h3> {{ c.title }}</h3>
    <h4> Available Assignments: </h4>
    <ul>
    {% for a in c.assignment_set.all %}
    <li><a href="/grading/student/{{ student_id }}/assignment/{{ a.id }}">Assignment {{ a.assignment_no }}, Due Date: {{ a.due_date }}</a></li>
    {% endfor %}
    </ul>
    <h4> Past Assignments: </h4>
    {% endfor %}
{% else %}
    <p>No courses are available.</p>
{% endif %}